# 使用语言
language: node_js

## node版本
node_js: stable

# 设置监听哪个分支
branches:
  only:
    - master
    - dev
    
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo generate
  - hexo generate
  - export HEXO_ALGOLIA_INDEXING_KEY=$ALGOLIA_KEY && hexo algolia

## 部署
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN 
  local_dir: ./public # 设置需要上传的目录
  target_branch: gh-pages
  keep_history: true
  on:
   all_branches: true
notifications:
  email: false

env:
  global:
    - GH_REF=github.com/fengxiu/blog.git
