# 使用语言
language: node_js
## node版本
node_js: stable
# 设置监听哪个分支
branches:
  only:
    - master
    - dev
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
  - npm install -g hexo-cli
install:
  # 不用yarn的话这里改成 npm i 即可
  - npm install
script:
  - hexo clean
  - hexo generate
  - hexo generate
  - export HEXO_ALGOLIA_INDEXING_KEY=d55e0adb332e8d9ef9023a6b4afd46f1 && hexo algolia

# after_success:
#   - cd ./public
#   - git init
#   - git config user.name  "zhangke"
#   - git config user.email "398757724@qq.com"
#   - git add --all
#   - git commit -m "version 1"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: ./public # 设置需要上传的目录
  target_branch: gh-pages
  keep_history: true
  on:
   all_branches: true
   condition: $TRAVIS_BRANCH =dev
notifications:
  email: false

env:
  global:
    - GH_REF=github.com/fengxiutianya/blog.git
