version: "3"
services:
  webapp:
    container_name: hexo
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/fengxiu/node
    working_dir: /root/hexo
    command: "npm run start"
    volumes:
      - "./:/root/hexo"
      - "./.ssh:/root/.ssh"
    ports:
      - "4000:4000"
