# 设置workflow 名称
name: Deploy Blog

# 触发条件
on: 
  push:
    branches: 
      - master
  watch:
    types: [started]
# 任务
jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v3 # 脚本来自 https://github.com/actions/checkout
        with:
          submodules: true
      ## 配置node
      - name: node # 配置Node环境
        uses: actions/setup-node@v4 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: 18
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      ## 安装依赖
      - name: Install
        run: |
          npm -v
          npm i -g hexo-cli --unsafe-perm=true --allow-root # 安装hexo
          npm i
  
      # - name: generate
      #   run: |
      #     hexo clean && hexo generate && hexo clean
      #     git config --global user.name 'fengxiu'
      #     git config --global user.email 'fengxiu.zk@alibaba-inc.com'
      #     echo  $(date)  > date.txt
      #     git add -A 
      #     git commit -m "${{ github.event.head_commit.message }}-generate-abbrlink" 
      #     git push origin master
    # Deploy hexo blog website.
      - name: Deploy
        id: deploy
        uses: sma11black/hexo-action@v1.0.2
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          user_name: fengxiu  # (or delete this input setting to use bot account)
          user_email: zhangkefengxiu@gmail.com  # (or delete this input setting to use bot account)
          commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)
