# 设置workflow 名称
name: Deploy Blog

# 触发条件
on: 
  push:
    branches: 
      - mastert
      - dev
# 任务
jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 10.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "10.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        HEXO_ALGOLIA_INDEXING_KEY: ${{secrets.ALGOLIA_KEY}}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'fengxiu' # 换成你自己的邮箱和名字
        git config --global user.email 'zhangkefengxiu@gmail.com'
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
  
    - name: Deploy
      run: |
        ## clean
        hexo clean
        ## generate
        hexo generate
        ## algolia 用于搜索
        ## export HEXO_ALGOLIA_INDEXING_KEY=$ALGOLIA_KEY && hexo algolia
        hexo deploy
        
        
        
        

