name: Pages

on:
  push:
    branches:
      - master # 我们设置的分支是 gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
          path: blog
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "20.11.1"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
        working-directory: ./blog

      - name: Build
        run: npm run build
        working-directory: ./blog

      - name: Upload Pages artifact
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./blog/public
          external_repository: fengxiu/blogpage # 更改为你的 GitHub Pages 仓库, username 是你的用户名
          publish_branch: main # GitHub Pages 分支
